version: '3'
services:
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        volumes:
            - ./back/src:/var/www/html/
        ports:
            - 8000:80

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: apitoken
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: 'admin'
        volumes:
            - ./apitoken.sql:/docker-entrypoint-initdb.d/apitoken.sql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1