
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: apitoken
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: 'admin'
        volumes:
            - ./datas:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1